name: Test Release

on:
  push:
    tags:
      - 'v*-beta*'

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    
    - name: Set up Python
      run: uv python install 3.12
    
    - name: Build package
      run: |
        uv build
    
    - name: Check package
      run: |
        uv run twine check dist/*
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-packages
        path: dist/

  publish-to-testpypi:
    name: Publish to TestPyPI
    needs: build-and-test
    runs-on: ubuntu-latest
    
    environment:
      name: testpypi
      url: https://test.pypi.org/project/mcp-deadmansnitch/
    
    permissions:
      id-token: write
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-packages
        path: dist/
    
    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
    
    - name: Wait for TestPyPI to update
      run: sleep 30
    
    - name: Test installation from TestPyPI
      run: |
        # Create a test virtual environment
        python -m venv test-env
        source test-env/bin/activate
        
        # Extract version from dist files
        VERSION=$(ls dist/*.whl | sed -E 's/.*-([0-9]+\.[0-9]+\.[0-9]+beta[0-9]+).*/\1/')
        
        # Install from TestPyPI
        pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ mcp-deadmansnitch==$VERSION
        
        # Basic smoke test
        mcp-deadmansnitch --help